Release/segundo parcial
carolosano/carolosano.github.io pull request #10
Opened 2024-11-29 00:04 UTC by carolosano

2024-11-30 20:37 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA**:
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Asincronía y Manejo de Datos (3 puntos)**
⚠️ 0.5 puntos: Utiliza AJAX y JSON para obtener datos de forma asíncrona, pero no manejando adecuadamente promises y fetch para consumir alguna API mock .
❌ 0 puntos: La información estática no esta en formato JSON, no se se carga y utiliza de manera asíncrona. Los packs estan estaticos en el código, deberian estar en JSON.
❌ 0 puntos: Recorrido de colecciones siendo óptimo utilizando funciones de orden superior. No se renderiza correctamente lo obtenido de la api, se imprime en el HTML sin usar DOM.

- **Gestión del Proyecto y Buenas Prácticas con GitHub (7 puntos)**:
✅ 1 punto: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
✅ 1 punto: Creación de una rama release/segundo-parcial a partir de la rama develop utilizando Git.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama feature/cuarta-entrega con develop en GitHub.
✅ 1 punto: Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama release/segundo-parcial como parte de la entrega.
❌ 0 puntos: No Implementa un archivo [CHANGELOG.md](https://github.com/Laboratoria/changelog-guide) documentando los cambios realizados en el proyecto en cada entrega o versión, siguiendo un formato estructurado.
❌ 0 puntos: No Configura [reglas en GitHub](https://docs.github.com/es/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) para bloquear push directos a las ramas develop y master, exigiendo pull requests con al menos un revisor aprobado para realizar merges. Incluir en el comentario de la pull request una captura con el estado de las reglas.
❌ 0 puntos: No Implementa una [plantilla (template) de pull request](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) en el repositorio para estandarizar las solicitudes de revisión y asegurarse de incluir in[formación relevante](https://axolo.co/blog/p/part-3-github-pull-request-template) (descripción, cambios realizados, pruebas realizadas, etc.).

**Nota**: 4(Cuatro)

**Comentarios**: En primer lugar, quiero reconocer el esfuerzo que pusiste en el proyecto. Sin embargo, hay varias áreas que necesitan atención para mejorar la cohesión y funcionalidad de tu trabajo, y poder aprobar el final de la materia.

- **Enfoque en el Simulador:** Parece que algunas características están un poco desconectadas del objetivo principal. Por ejemplo, imprimir una lista de usuarios no parece tener una relación lógica con la funcionalidad de los packs. Es importante que tu implementación sea coherente y que todas las piezas trabajen juntas en función del objetivo del simulador. Recomendación: Define claramente el propósito del simulador y revisa el diseño para asegurar que todos los componentes interactúen de manera significativa.

- **Asincronía y Manejo de Datos:** Aunque comenzaste a implementar AJAX y JSON, sería beneficioso abordar cómo se estructuran los datos. Considera mover los packs a un archivo JSON y cargarlos de manera asíncrona. Esto no solo mejora la organización, sino que también te ayuda a ganar puntos en la evaluación. Además, usa funciones de orden superior para recorrer y manipular colecciones de datos.

- **Buenas Prácticas en GitHub:** Existen áreas claras de mejora aca. Asegúrate de configurar correctamente tu flujo de trabajo en GitHub:
  - Implementa un `CHANGELOG.md` para llevar un registro de los cambios realizados en cada versión.
  - Configura reglas en las ramas principales para evitar pushes directos y exigir revisiones aprobadas. (tenes que incluir una captura, como pide la consigna)
  - Crea una plantilla para pull requests que facilite la revisión y la documentación de cambios efectuados.

- **Preparación para el Final:** Considera que este proyecto debe estar listo para ser defendido en el examen final. Intenta trabajar más en la cohesión y propósito del proyecto, asegurándote de que cada componente contribuya positivamente al simulador total.

Con estos ajustes y un enfoque claro, tu proyecto puede mejorar significativamente. ¡Ánimo y seguí adelante, que estás en el camino correcto para obtener un resultado más sólido!

2024-11-30 20:37 UTC, MVelasquez98 commented on CHANGELOG.md
Esto esta incompleto, no solo es una plantilla, tenes que rellenarlo, con todo lo que hiciste en el proyecto, Actividades Obligatorias 1, 2, 3 y 4. Primer y Segundo Parcial, incluir fechas, linkear las pull request.

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +  const newUser = {
¿Y esto que tiene que ver con el pryecto?

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +  outputDiv.innerHTML = `<pre>${JSON.stringify(data, null, 2)}</pre>`;
No es la idea del uso de una api, estas literalmente imprimiendo el JSON en el HTML:
![image](https://github.com/user-attachments/assets/93393cec-686d-476f-8761-b20c554689f6)
Tenes que trabajar con esta información y el uso de  DOM, además que la información debe ser relevante para el proyecto ¿de que sirve en un sitio de "packs" imprimir una lista de usuarios?

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +const apiBaseUrl = 'https://6748dd015801f515359267a4.mockapi.io/c1/productos';
Creo que no tiene mucho sentido el mock que escogiste, ¿porque no tener los packs en la API y renderizarlos en el listado a escoger, en vez de que esten el html estatico?

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +  const packGrafico = new Producto(
Estos packs son los que tienen que estar en un JSON aparte y consumir mediante fetch. 
`api/packs.json`

2024-11-30 20:37 UTC, MVelasquez98 commented on packAlternativo.js
Si esto es una clase, el nombre del archivo es PackAlternativo.js, usamos siempre PascalCase para el nombre de las Clases

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +import PackAlternativo from "./packAlternativo.js";
Si esto es una clase, el nombre del archivo es PackAlternativo.js, usamos siempre PascalCase para el nombre de las Clases

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +import { Producto } from "./Producto.js";
Las `{ }` son innecesarias

2024-11-30 20:37 UTC, MVelasquez98 commented on Producto.js
> +export { Producto };
Las `{ }` son innecesarias

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +
Enciérralo en un bloque try-catch para capturar cualquier error inesperado y realizar una acción adecuada, como registrar el error o mostrar un mensaje de advertencia al usuario.
```suggestion
try {
```

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +});
```suggestion
catch (error) {
     console.error('Error en el envío del formulario:', error);
  }
});
```

2024-11-30 20:37 UTC, MVelasquez98 commented on script.js
> +      if (!response.ok) throw new Error('Error al obtener los datos');
Sumar un
`   console.error('Error:', error);
`

2024-12-01 14:20 UTC, carolosano commented
@MVelasquez98 perfecto profe voy a ir haciendo estas correcciones, hasta cuando tengo tiempo de seguir perfeccionando el proyecto?

2025-07-24 20:46 UTC, carolosano commented
@MVelasquez98 Hola profe, como le va tanto tiempo? Acá corregí lois cambios del segundo parcial que me quedaron pendientes, le pongo acá lo que me había corregido la ultima vez y fuí corrigiendo todos los puntos a continuaciòn:

⚠️ 0.5 puntos: Utiliza AJAX y JSON para obtener datos de forma asíncrona, pero no manejando adecuadamente promises y fetch para consumir alguna API mock .
❌ 0 puntos: La información estática no esta en formato JSON, no se se carga y utiliza de manera asíncrona. Los packs estan estaticos en el código, deberian estar en JSON.
❌ 0 puntos: Recorrido de colecciones siendo óptimo utilizando funciones de orden superior. No se renderiza correctamente lo obtenido de la api, se imprime en el HTML sin usar DOM.
❌ 0 puntos: No Implementa un archivo [CHANGELOG.md](https://github.com/Laboratoria/changelog-guide) documentando los cambios realizados en el proyecto en cada entrega o versión, siguiendo un formato estructurado.
❌ 0 puntos: No Configura [reglas en GitHub](https://docs.github.com/es/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) para bloquear push directos a las ramas develop y master, exigiendo pull requests con al menos un revisor aprobado para realizar merges. Incluir en el comentario de la pull request una captura con el estado de las reglas.
❌ 0 puntos: No Implementa una [plantilla (template) de pull request](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) en el repositorio para estandarizar las solicitudes de revisión y asegurarse de incluir in[formación relevante](https://axolo.co/blog/p/part-3-github-pull-request-template) (descripción, cambios realizados, pruebas realizadas, etc.).

2025-07-24 20:52 UTC, MVelasquez98 requested changes

2025-07-24 20:52 UTC, MVelasquez98 commented on pull_request_template.md
¿Por qué esta vacio? Tiene que ser justamente un template con todo lo necesario. Revisa la documentación, en que carpeta y demás. [doc github](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
Si esta bien configurado, ya deberías poder usar esta plantilla en esta misma pull request.

2025-07-24 20:54 UTC, MVelasquez98 commented
Las reglas de github siguen mal configuradas.
Como se ve en tu repositorio:
<img width="948" height="398" alt="image" src="https://github.com/user-attachments/assets/7dac7b03-7011-4470-9212-d2927afed875" />
Como se tendría que ver:
<img width="924" height="242" alt="image" src="https://github.com/user-attachments/assets/09c13201-6c7e-49c1-ad6a-ea8e0989d6e0" />
El [video](https://youtu.be/qe6mPZXDNRM) explicativo del campus

2025-07-24 20:56 UTC, MVelasquez98 requested changes

2025-07-24 20:56 UTC, MVelasquez98 commented on CHANGELOG.md
> +## [2.2.0] - 2025-07-24
No usamos numeros de versiones en ningun momento, en el changelog van todas las actividades obligatorias y parciales, enlazados correctamente en markdown la pr correspondiente

2025-07-24 21:12 UTC, MVelasquez98 requested changes
<img width="395" height="579" alt="image" src="https://github.com/user-attachments/assets/9496ceaa-2921-4ae3-b413-5d7db5ab2a2c" />
Es bastante confuso para un carrito, hay productos repetidos, nunca se entiende de que pack vienen ¿se puede mejorar la experiencia de usuario? Diferenciando los paquetes en el carrito y tambien si estan repetidos agrupar con cantidad. Por otro lado, si agrego un pack personalizado se sobreescribe el carrito ¿es un comportamiento deseado?

2025-07-24 21:18 UTC, carolosano commented
> Las reglas de github siguen mal configuradas. Como se ve en tu repositorio: <img alt="image" width="948" height="398" src="https://private-user-images.githubusercontent.com/43156596/470525788-7dac7b03-7011-4470-9212-d2927afed875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMzOTIxODMsIm5iZiI6MTc1MzM5MTg4MywicGF0aCI6Ii80MzE1NjU5Ni80NzA1MjU3ODgtN2RhYzdiMDMtNzAxMS00NDcwLTkyMTItZDI5MjdhZmVkODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI0VDIxMTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNTE4ZGZlYTI4NjlmMjVlZWIyZDU2ZjM5YjAwNWE0NGJiZjA2MjU5MjY4NDA3ODEwOWNmZDNhZGNmYzNmNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yg4_86Moh8L_G2uNOm2lq30Mj4Y6JciJ4ytne3LTXzg"> Como se tendría que ver: <img alt="image" width="924" height="242" src="https://private-user-images.githubusercontent.com/43156596/470526113-09c13201-6c7e-49c1-ad6a-ea8e0989d6e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMzOTIxODMsIm5iZiI6MTc1MzM5MTg4MywicGF0aCI6Ii80MzE1NjU5Ni80NzA1MjYxMTMtMDljMTMyMDEtNmM3ZS00OWMxLWFkNmEtZWE4ZTA5ODlkNmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzI0VDIxMTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NTg4M2E1Njk5NDUwYTlmMjhkNTViMjZkOGI3N2FkNmYyMGNhYWE4OTU3MDcxMTA3ZTdkMTFlOTYxYTA1NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JovhSWPjRIHV7YlX9PZWhHNl9syQXM8GglzzKwde8J4"> El [video](https://youtu.be/qe6mPZXDNRM) explicativo del campus

Okei perfecto, ahi lo hice para los Release/**

2025-07-24 21:22 UTC, carolosano commented on pull_request_template.md
<img width="1917" height="348" alt="Captura de pantalla 2025-07-24 a las 6 20 00 p  m" src="https://github.com/user-attachments/assets/1f81d880-b03f-46db-9458-9e39b0e54926" />
ahi vi la documentacion, se me hace un poco confuso, perdon profe, asi seria? la plantilla

2025-07-24 21:42 UTC, MVelasquez98 commented
Las reglas siguen mal configuradas, la protección es para la rama máster, que es hacia donde estás haciendo la pull request, revisa la pr, mientras te deje hacer merge en verde, sigue mal configurada. Tiene que estar bloqueada en rojo esperando mi aprobación, como te mostré en la imagen

2025-07-24 21:47 UTC, carolosano commented
> Las reglas siguen mal configuradas, la protección es para la rama máster, que es hacia donde estás haciendo la pull request, revisa la pr, mientras te deje hacer merge en verde, sigue mal configurada. Tiene que estar bloqueada en rojo esperando mi aprobación, como te mostré en la imagen

@MVelasquez98 Ah perfectop, ahi lo configure para que sea a la rama master las reglas. Camie el archivo CHANGELOG.md y puse el template en el pull_request_template. Me podría profe decir si es que lo hice bien o sigue algo mal? vi su video explicativo, fue de mucha ayuda, lo que nose si entendí bien fue la documentacion para el template, pero creo q lo pude hacer. Ahora sigo con los cambios en el carrito que me pidió

2025-07-25 01:16 UTC, MVelasquez98 submitted a review, later dismissed
LGTM

2025-07-25 01:30 UTC, carolosano commented
@MVelasquez98 nose que hice que ahora no puedo hacer merge profe :(. mE podria ayudar?

2025-07-25 01:34 UTC, MVelasquez98 commented
La reléase está aprobada solo tenes que hacer merge, el anexo no entra en esta reléase igual

2025-07-25 01:37 UTC, carolosano commented
> La reléase está aprobada solo tenes que hacer merge, el anexo no entra en esta reléase igual

Me aparece esto de que hay conflictos
<img width="1077" height="507" alt="Captura de pantalla 2025-07-24 a las 10 36 21 p  m" src="https://github.com/user-attachments/assets/8e69a8b4-9c2c-4f2f-bacf-793ae825708e" />

2025-07-25 01:41 UTC, MVelasquez98 commented
Eso es porque agregaste el anexo antes, tenes conflictos de merge, tenes que resolverlos en tu local y volver a hacer push. Baja con pull lo último de develop y después hace rebase and merge de la rama de la reléase con develop, ahí te van aparecer todos los conflictos y tenes para aceptar los cambios. Una vez que esté listo, haces commit y un git push -f

2025-07-25 01:49 UTC, MVelasquez98 commented
Ya no tenes más conflictos si te doy aprobación?

2025-07-25 01:52 UTC, MVelasquez98 approved these changes
LGTM

2025-07-25 01:53 UTC, carolosano commented
Lo que hice fue sacar primero anexo y el resto y hacer push pero todavia o hice lo de develop con el pull lo estoy tratando de hacer ahora profe.

2025-07-25 01:53 UTC, MVelasquez98 commented
Récorda es MERGE PULL REQUEST cuándo es reléase, está en la consigna. No es rebase and merge, eso es solo con develop. Seguí el instructivo de la consigna

2025-07-25 01:54 UTC, MVelasquez98 commented
Tenes para escoger en el botón alguna de las dos opciones

2025-07-25 01:55 UTC, MVelasquez98 commented
![IMG_3520](https://github.com/user-attachments/assets/3a644f31-e237-45d8-a266-1d0ad75c89b1)

2025-07-25 02:05 UTC, carolosano commented
> ![IMG_3520](https://private-user-images.githubusercontent.com/43156596/470594696-3a644f31-e237-45d8-a266-1d0ad75c89b1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0MDkzMTMsIm5iZiI6MTc1MzQwOTAxMywicGF0aCI6Ii80MzE1NjU5Ni80NzA1OTQ2OTYtM2E2NDRmMzEtZTIzNy00NWQ4LWEyNjYtMWQwYWQ3NWM4OWIxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyNVQwMjAzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTc3M2NkMDllZmJkN2U4OTU5MzU2YTcwZDNjZThlOWY5ODQ3YWM1NDFjMTAwZjI4MDlmYTI3YzU2YjQyY2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rLBZm-w5orbwtN_3hNXdx7BJ4dFuGThYmy4gPaXOEhc)

aa que raro porque a mi me aparece esto profe por eso
![Uploading Captura de pantalla 2025-07-24 a las 11.05.26 p. m..png…]()

2025-07-25 02:08 UTC, carolosano commented
> ![IMG_3520](https://private-user-images.githubusercontent.com/43156596/470594696-3a644f31-e237-45d8-a266-1d0ad75c89b1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0MDk1ODAsIm5iZiI6MTc1MzQwOTI4MCwicGF0aCI6Ii80MzE1NjU5Ni80NzA1OTQ2OTYtM2E2NDRmMzEtZTIzNy00NWQ4LWEyNjYtMWQwYWQ3NWM4OWIxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyNVQwMjA4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDE0Y2RjYzVhMDhmYzlmNTYxOTk5ZmEzMGEwZjdmMDkyZmMxMjYyOGMwNTgxNTQyMWU1ZDM0MTllM2Q0ZWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aAY1I-HIbgF8RitLT8XRB885eRbgkC-tBtmygOT8BdQ)

aite juro estoy desesperadaporque no entiendonpor que no me dice ese boton !!

2025-07-25 02:15 UTC, merged