prueba para ver si hago el push
carolosano/carolosano.github.io pull request #2
Opened 2024-09-17 01:49 UTC by carolosano

hola profe 

acá agregué lo que me quedaba de los **estilos de CSS**  que te dije que me faltaban desarrollar pero **me parece que me** **mande una cagada** porque estuve laburando en la rama **feature/primer-entrega** y no en la **feature/segunda-entrega.** 

**Elijo creer que no voy a cagar** los cambios de tus correcciones. Te pido mil disculpas por adelantado si la cago después de escribirte este mensaje :) R.I.P.

2024-09-17 01:52 UTC, carolosano commented
dejo otro comentario adjuntandofoto de algunos estilos que le puse por si no se ven en este merge :(
<img width="1500" alt="Captura de pantalla 2024-09-16 a las 10 50 46 p  m" src="https://github.com/user-attachments/assets/d63abe5d-8a51-48af-81c9-5652440e1caf">

2024-09-17 01:54 UTC, carolosano commented
VAMOOO PROFE LO HICE BIENN :)))))))

2024-09-17 01:54 UTC, carolosano commented
creo..

2024-09-17 02:24 UTC, MVelasquez98 commented
@carolosano Carolina, antes que cierre la entrega, fijate que estuviste trabajando los cambios en **feature/primera-entrega**, y en el enlace de github pages que pasaste se ven estilos muy basicos. Fijate el files changed el css de esta pull request no es el mismo que el de la captura. Por otro lado, no esta cerrada la primera entrega. Si no haces rebase and merge de la primera PR, esos cambios nunca van a estar en develop

2024-09-25 16:00 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Mejoras en la Maquetación CSS (5 puntos):**
- Implementación eficaz de diferentes tipos de selectores y aprovechamiento de la herencia de estilos para simplificar el código CSS. (1 punto) ✔️
- Aplicación correcta de formatos y fuentes para mejorar la legibilidad y estética del contenido, utilizando las propiedades CSS correspondientes. (1 punto) ✔️
- Uso adecuado de modelos de caja (box model) para controlar el tamaño, margen, relleno y bordes de los elementos de la página. (1 punto) ❌
- Diferenciación clara entre elementos en línea y elementos en bloque mediante estilos CSS apropiados, demostrando comprensión de las diferencias y su aplicación en el diseño web. (1 punto) ❌
- Implementación efectiva de columnas utilizando técnicas como elementos flotantes, display: flex y display: grid, según corresponda al diseño requerido. (1 punto) ❌ Falta el uso de Grid y Flex para la estructura de la pagina.

**Diseño de Columnas y Layouts Responsive (2 puntos):**
- Correcta utilización de media queries para crear un diseño responsive que se adapte de manera adecuada a diferentes tamaños de pantalla y dispositivos. (1 punto)❌
- Estructuración satisfactoria de layouts utilizando contenedores, filas y columnas, demostrando comprensión de los conceptos de diseño responsivo y su aplicación práctica. (1 punto)❌ Hace uso de Flexbox en todo el documento, eso va mejorar la UX, sobre todo en dispositivos moviles. Podes ver como se vería tu página en un celular desde el inspector de chrome o el navegador que utilices

**GitHub (3 puntos):**
- Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto) ⚠️ Se hicieron commits sobre la rama feature/primera-entrega, no en la rama feature/segunda-entrega, por eso no se ve reflajado en los archivos de esta pull request. Tenes un interesante problema para resolver en el parcial, tenes que lograr que esos cambios que dejaste en la rama feature/primera-entrega esten ahora en feature/segunda-entrega, para poder realizar la correcta PR, pero antes que nada cerra la primera pull request, para que la primera entrega quede en develop
- Creación de una rama "feature/segunda-entrega" a partir de la rama "develop" utilizando Git. (1 punto)  ❌ La rama actual, no contiene los últimos cambios de develop, porque no se cerro la primera pull request
- Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/primera-entrega" con "develop" en GitHub. (1 punto)  ❌ La PR esta abierta, nunca se cerro despues de la aprobación

**Nota:** 2 (dos).
**Comentario** Imagino que mucho de los cambios estan en otra rama, pero no lo veo reflejado en la entrega.

2024-10-01 20:00 UTC, carolosano reviewed
@MVelasquez98 hola profe hoy es martes 1 de octubre,  te comento devuelta porque ahi me parece que pude hacer bien el merge de la primera entrega como me dijiste y el push a la segunda entrega desde el repo local. Decime si esta bien asi, desde pages yo puedo ver los nuevos cambios. Cualquier cosa quedo atenta

2024-10-01 20:08 UTC, MVelasquez98 commented
Aunque te de approve no te va dejar hacer merge, por los [conflictos](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) que hay:
<img width="893" alt="image" src="https://github.com/user-attachments/assets/d04becc5-9603-410b-9862-e9d38de73d4a">
Podes hacer lo siguiente en tu local:

- Te moves a origin/develop
- Haces git pull
- Volves a la rama feature/segunda-entrega
- Haces desde vscode ... -> Rama -> Fusionar la rama mediante "rebase"

![image](https://github.com/user-attachments/assets/ac60e795-fece-42ae-9c91-20672e16630d)

- Escoges origin/develop del listado.
- [Resolves los conflictos](https://www.jorgeacortes.com/2019/01/resolver-conflictos-en-git-con-visual-studio-code/)que esten en los archivos marcados con advertencia ⚠️
- Asegurate de no pisar tus cambios
- Hace git add .
- Le das "Continuar" (el boton azul)
- Haces git push -f

Algunos videos que te pueden servir:
[Como Solucionar un Merge Conflict (Conflicto de Merge) En VSCode](https://youtu.be/uDDNwwxoaZY?si=eGG_ZhIXRfYpEmnn)
[Cómo resolver conflictos de versiones con VS Code](https://youtu.be/g7bbxEt09PI?si=bi26br5lpoyPY3-w)

2024-10-01 22:34 UTC, carolosano commented
@MVelasquez98 ahi hice lo que me dijiste. Creo que ya estarían corregidos los errores? o estoy equivocada?

2024-10-01 22:36 UTC, carolosano commented
me parece que no pise el código... soy el meme de "dios te pido q nos ayudes"

2024-10-02 15:19 UTC, MVelasquez98 commented
Ya no tenes concflictos de merge, pero esta pr solo agrega esto:
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/287b6376-264c-4d3a-acdb-a7f9b4a8f37c">
Eso se debe a que hiciste push de los cambios directamente sobre develop, pasando por alto la pull request:
<img width="965" alt="image" src="https://github.com/user-attachments/assets/517a6d4e-1f4b-451a-95f1-a5ec7199b210">

2024-10-02 15:21 UTC, MVelasquez98 approved these changes
LGTM
Te doy approve para que continues con el flujo normal con el parcial, pero tene en cuenta que se te va descontar puntos por no hacer uso de GitFlow como venimos haciendo en el resto de entregas.

2024-10-02 18:38 UTC, merged