Release/primer parcial
carolosano/carolosano.github.io pull request #3
Opened 2024-10-03 13:45 UTC by carolosano

Hago la pull request de la rama release/primer parcial para master. @MVelasquez98

2024-10-04 18:28 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

**Incorporación de Componentes Avanzados de HTML (1 punto):**

- ✅ Agregar al menos un componente avanzado de HTML a la página, como un iframe de un video de YouTube o un mapa de Google Maps. (1 punto).

**Implementación de Bootstrap para Diseño Responsivo (5 puntos):**

- ✅ Instalar la biblioteca Bootstrap en el proyecto. (1 punto)
- ❌ Utilizar el sistema de columnas de Bootstrap para hacer que el sitio sea más responsivo en dispositivos móviles. (3 puntos). Podría aprovecharse mejor el [sistema de columnas en Bootstrap](https://getbootstrap.esdocu.com/docs/5.1/layout/columns/) o [grilla](https://getbootstrap.com/docs/4.0/layout/grid/) para mejorar el [Diseño UI](https://perio.unlp.edu.ar/catedras/comyddhhlic/wp-content/uploads/sites/125/2023/02/Diseno-UX-UI.pdf), más que nada en dispositivos moviles. 
- ❌ Incluir al menos un componente avanzado de Bootstrap, como un carrusel, una barra de navegación o un modal. (1 punto)

**Gestión del Proyecto con GitHub (4 puntos):**

- ✅ Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto)
- ✅ Creación de una rama "release/primer-parcial" a partir de la rama "develop" utilizando Git. (1 punto)
- ❌ Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/segunda-entrega" con "develop" en GitHub. (1 punto)
-  ✅ Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama "release/primer-parcial" como parte de la entrega. (1 punto)

**Nota:** 7 (Siete)

2024-10-22 18:27 UTC, carolosano commented
@MVelasquez98 hola profe. aca hice los cambios que me pediste. Lo que me genera DUDAS es que tanto la navBar como el Carrousel nose por que no funcionan cuando los clikeo. estuve viendo posibles errores pero no funciona.

2024-10-22 18:46 UTC, MVelasquez98 commented
@carolosano El carrousel y el navbar no funcionan bien porque no instalaste correctamente Bootstrap. Fijate la [documentación](https://getbootstrap.com/docs/5.3/getting-started/introduction/#quick-start). Si no seguis todos los pasos de importación de forma correcta, no vas a poder usar todos los efectos de la libreria.
![image](https://github.com/user-attachments/assets/2de63c9f-9f18-4f01-9e31-26ee0df0a075)

2024-10-22 19:29 UTC, carolosano commented
Ahh ahi lo hice. Ya se puede mover el carrousel y clickear en la nabab y funciona :) . Mi otra duda es que lo de JS que tenemos que agregar lo tengo que hacer despues una vez que me des LGTM en este pull no? @MVelasquez98

2024-10-22 19:42 UTC, MVelasquez98 approved these changes
Buenisimo. Fijate que todavía te falta arreglar lo del formulario:
![image](https://github.com/user-attachments/assets/c5a44f9e-ec61-42a5-b86e-bf4f96181055)
Podes aprovecharte de los [formularios](https://getbootstrap.com/docs/4.0/components/forms/) en Bootstrap para mejorar el diseño responsivo.
El [textarea](https://getbootstrap.com/docs/5.3/forms/floating-labels/#textareas) que tiene un **col=50** es un ancho fijo, por lo que te esta empujando todo el contenido en pantallas pequeñas.

Te doy LGTM asi avanzas con la entrega 3, corregí esto en la tercera entrega

2024-10-22 19:42 UTC, MVelasquez98 commented on index.html
> +            <nav class="navbar navbar-expand-lg bg-body-tertiary">
No esta funcionando el navbar en dispositivos moviles:
![image](https://github.com/user-attachments/assets/e43deb9e-5c0d-4630-a569-b15d5cff877e)

2024-10-22 19:42 UTC, MVelasquez98 commented on index.html
> +            <form action="" method="">
El formulario no se comporta de forma responsiva en dispositivos moviles:
![image](https://github.com/user-attachments/assets/511abce5-2c91-4401-817e-b5aef6030e94)
Podes aprovecharte de los [formularios](https://getbootstrap.com/docs/4.0/components/forms/) en Bootstrap para mejorar el diseño responsivo.

2024-10-22 19:42 UTC, MVelasquez98 commented on index.html
> +                      <a class="nav-link active" aria-current="page" href="#">Inicio</a>
Reemplaza la almohadilla # por la url o seccion de la página correspondiente a la que direccionan los enlaces del menu.

2024-10-22 19:42 UTC, MVelasquez98 commented on index.html
> +            <form action="" method="">
Esto se sigue viendo igual en dispositivos moviles. Lo podes ver desde el inspector de tu navegador:
![image](https://github.com/user-attachments/assets/cd75ca8b-6571-41f5-b111-36f40e3fb13f)

2024-10-22 19:54 UTC, merged