Implementación de cambios adicionales para la tercera entrega
carolosano/carolosano.github.io pull request #7
Opened 2024-10-23 00:28 UTC by carolosano

Hola profe, no llegue con el tiempo para arreglar la parte responsive que me dijiste pero voy haciendo los commits necesarios post esta entrega lo juro. :)

2024-10-24 18:17 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Algoritmos (1 punto)**
❌  0 puntos: Uso incorrecto o ineficiente de algoritmos condicionales y ciclos. No estas usando switch, no estas usando un ciclo para el menu, solo se va ver una vez.

- **Funciones (1 punto)**
❌ 0 puntos: Funciones con nombres confusos, estructura incorrecta o resultados incorrectos. Estas confundiendo funciones con clases en sintaxis. Recorda que funciones y métodos son diferentes sintaxis.

- **Funcionalidad (1 punto)**
❌  0 puntos: Flujo de trabajo incompleto o funcionalidad inapropiada al contexto. Tu algoritmo no resuelve nada funcional para la pagina, solo hay una validación de un nombre y una validación de formulario (que utiliza eventos y DOM que no vimos en la unidad y no entra en esta entrega). Se espera algun algoritmo relacionado con calcular un precio, filtrar o buscar productos, armar un carrito de compras, etc. El menu propuesto de agregarPack es interesante, pero nunca se llama de ningun lado.

- **Interactividad (1 punto)**
⚠️ 0.5 puntos: Interactividad insuficiente o salidas incoherentes. Hay un solo prompt pidiendo el nombre, el resto de entradas son con DOM, que no entra en esta entrega.

- **Escalabilidad (1 punto)**
❌ 0 puntos: Falta de funciones con parámetros, arrays o objetos relevantes. No utilizas clases ni métodos con la sintaxis correcta, no utilizas arrays.

- **Legibilidad (1 punto)**
⚠️ 0.5 puntos: Nombres de variables, funciones u objetos poco significativos, código ilegible o mal estructurado. Cuesta seguir el hilo de cual es la funcionalidad que estas buscando, seprar correctamente las clases en archivos separaos y definir correctamente las funciones te va ayudar.
**GitHub (4 puntos):**
- ✅ 1 punto: Creación de una rama "backport/primer-parcial" a partir de la rama "master" utilizando Git.
- ✅ 1 punto: Creación de una rama "feature/tercera-entrega" a partir de la rama "develop" utilizando Git.
- ⚠️ 0.5 puntos:: Correcta realización de la solicitud de revisión para fusionar la rama "backport/primer-parcial" con "develop" en GitHub, resolviendo los conflictos de merge (si fuese necesario). Cuidado con las pr cerradas sin merge, no es una buena practica, en algunos lugares esto reporta una métrica negativa.
- ⚠️ 0.5 puntos: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "release/primer-parcial" con "master" en GitHub,  resolviendo los conflictos de merge (si fuese necesario). Faltaron puntos de responsive por solucionar, entre los cambios solicitados.

**Nota**:

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +document.getElementById('btn').addEventListener('click', function(event) {
No entra en esta entrega el uso de DOM, estos son los unicos temas de la unidad:
![image](https://github.com/user-attachments/assets/b63fc739-6b00-4bde-8243-0d2929c1af35)
⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +    event.preventDefault();  // Prevenir el envío del formulario
No entra en esta entrega el uso de Eventos, estos son los unicos temas de la unidad:
![image](https://github.com/user-attachments/assets/b63fc739-6b00-4bde-8243-0d2929c1af35)
⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +function Cliente(nombre, email) {
¿Esto es una Clase? ¿Porque tiene la sintaxis de function y no de class? Revisar la [sintaxis](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes) correcta, además como dijimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009), es propio tener las clases en un archivo aparte.

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +    this.mostrarInfo = function() {
No es la sintaxis correcta de [métodos](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes#m%C3%A9todos_prototipo), suponiendo que se trate de eso. Revisar

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +function Consulta(cliente, mensaje) {
¿Esto es una Clase? ¿Porque tiene la sintaxis de function y no de class? Revisar la [sintaxis](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes) correcta, además como dijimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009), es propio tener las clases en un archivo aparte.

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +    this.mostrarConsulta = function() {
No es la sintaxis correcta de [métodos](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes#m%C3%A9todos_prototipo), suponiendo que se trate de eso. Revisar

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +    var nombre = document.getElementById('nombre').value;
No entra en esta entrega el uso de DOM, estos son los unicos temas de la unidad:
![image](https://github.com/user-attachments/assets/b63fc739-6b00-4bde-8243-0d2929c1af35)
⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +    if (packSeleccionado === "1") {
Considerar utilizar un [switch](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Statements/switch), como se explica en la unidad. Los if anidados no son una buena práctica, se te va escapar alguna opción

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +function saludar(nombre, mensaje) {
Carece de sentido esta función

2024-10-24 18:17 UTC, MVelasquez98 commented on script.js
> +function elegirPack() {
Esta funcion nunca se llama en ningun lado, si la función no se invoca en el root esta nunca se ejecuta.

2024-11-19 02:37 UTC, carolosano commented
Hola profe. @MVelasquez98  estuve haciendo varios cambios no solo con respecto a la estética sino también a la funcionalidad de los packs y eso. Usé tailwind (**consulto para saber si es legal en este tp usarlo**), porque es como bootstrap en donde saco componentes de ahi y me gustó mucho mas. Aclaro también que hay una carpeta node modules y packaje.json porque instalé algunas dependencias de css pero al final **no termine usando ninguna**, y me da inseguridad borrarlo sin saber si me cambia el codigo asi que despues veo como las borro sin repercusiones.

Lo unico que **sé que me equivoqué** es que hice lo del DOM y almacenar datos en el local Storage y eso lo tenia q hacer en la siguiente rama cuando me hayas dado LGTM, me di cuenta en el proceso despues de hacer eso asi que dejé algunas cosas para cuando tenga que agregar el resto de lo que pedís en la consigna de la U4.

2024-11-19 14:31 UTC, MVelasquez98 commented
Hola carolina, podes usar alguna lib adicional para estilos como tailwind, pero si vas a usar node con los paquetes de npm, tenes que crear en la raiz del proyecto un archivo `.gitignore` y dentro del archivo escribir todo lo que queres ignorar al subir a Git, por ejemplo `/node_modules/` (no es buena practica subir todos las dependencias de un proyecto). Podes leer más al respecto en la [documentación](https://docs.github.com/es/get-started/getting-started-with-git/ignoring-files?platform=windows) de Git. 
Por otro lado respecto a los cambios requeridos, ten en cuenta que en esta entrega que estas cerrando no entra DOM ni eventos, eso es de la entrega 4. Por lo que tenes que eliminar su uso en al menos esta rama, y utilizar prompt, alert, console.log. 
Más alla de los estilos tene en cuenta todos los cambios que te pedi que estan en pending.

2024-11-19 20:39 UTC, carolosano commented
@MVelasquez98 hola profe ahi saque todos los DOM. Utilice alerts, promts para **simular el funcionamiento del formulario** **de contacto**  utilizando una **función anejarFormulario** e hice que arme un objeto y me lo muestre en consola con la info del usuario y el mensaje:
<img width="384" alt="Captura de pantalla 2024-11-19 a las 5 38 30 p  m" src="https://github.com/user-attachments/assets/95201e37-f64c-4506-83f8-da6fb37e2b21">

Y para el **armar pack** use un **switch** para mostrar las opciones para armar el carrito. usaría la misma lógica para los dos packs predeterminados que hice.

2024-11-20 00:44 UTC, MVelasquez98 commented
Es `/node_modules`, fijate un [video](https://youtu.be/TLLzSvcoVQg?si=IWFtbnK_c04rfdL3) de referencia para que veas como se hace y como se deberia ver.
Si lo hiciste bien, cuando haces el commit y push, no deberia aparecer la carpeta node_modules en la pull request

2024-11-20 01:14 UTC, MVelasquez98 commented
El problema que tenes pasa  porque la carpeta node_modules ya estaba en el repositorio antes de agregar el .gitignore. El .gitignore solo evita que Git rastree nuevos archivos o cambios en archivos no rastreados, pero no tiene efecto en los archivos que ya están versionados en el repositorio.

- Primero, elimina node_modules del índice de Git sin borrar los archivos localmente:
`git rm -r --cached node_modules`
- Asegúrate de que node_modules se haya eliminado del índice y esté listo para el commit:
git status`
- Deberías ver algo como:
`deleted: node_modules/`
- Realiza un commit para registrar el cambio:
git commit -m "Eliminar node_modules del repositorio"
- Subi los cambios a la rama que tiene la pull request abierta:
git push

2024-11-20 01:16 UTC, carolosano commented
> El problema que tenes pasa porque la carpeta node_modules ya estaba en el repositorio antes de agregar el .gitignore. El .gitignore solo evita que Git rastree nuevos archivos o cambios en archivos no rastreados, pero no tiene efecto en los archivos que ya están versionados en el repositorio.
> 
> * Primero, elimina node_modules del índice de Git sin borrar los archivos localmente:
>   `git rm -r --cached node_modules`
> * Asegúrate de que node_modules se haya eliminado del índice y esté listo para el commit:
>   git status`
> * Deberías ver algo como:
>   `deleted: node_modules/`
> * Realiza un commit para registrar el cambio:
>   git commit -m "Eliminar node_modules del repositorio"
> * Subi los cambios a la rama que tiene la pull request abierta:
>   git push

AHI CREO QUE YA LO HICE MIRA
<img width="364" alt="Captura de pantalla 2024-11-19 a las 10 16 06 p  m" src="https://github.com/user-attachments/assets/9e7ac9c4-f660-48a8-b9a1-261d246067d5">

2024-11-20 01:44 UTC, carolosano commented
Okis genial, ya tengo el LGTM para hacer el rebase and merge?

2024-11-20 01:47 UTC, MVelasquez98 commented
Tenes que hacer los cambios que te mencione, son parte de la tercera entrega, y son cambios que no resolviste de la correción inicial.

2024-11-20 01:55 UTC, carolosano commented
> Tenes que hacer los cambios que te mencione, son parte de la tercera entrega, y son cambios que no resolviste de la correción inicial.

Ah pensé que ya había resuelto los cambios ahi voy mandando  los cambios que hice

2024-11-20 01:56 UTC, carolosano commented on script.js
> +document.getElementById('btn').addEventListener('click', function(event) {
> No entra en esta entrega el uso de DOM, estos son los unicos temas de la unidad: ![image](https://private-user-images.githubusercontent.com/43156596/379327955-b63fc739-6b00-4bde-8243-0d2929c1af35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjc3NTgsIm5iZiI6MTczMjA2NzQ1OCwicGF0aCI6Ii80MzE1NjU5Ni8zNzkzMjc5NTUtYjYzZmM3MzktNmIwMC00YmRlLTgyNDMtMGQyOTI5YzFhZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAxNTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZTY4NWVlZWEwNDU2YzY1YWRjZGNhOTk3MzcwYWE2MDM5NmQxOTc3ZTUwZWJjMjE2MjQ1MjQyZWM3ZDk3ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pcmGMtke5Ip2sq3sEGf5LGkJhwCVu6XZe4TFxQFd86s) ⚠️ Cuidado con el [feature creep](https://www.agile-academy.com/en/agile-dictionary/feature-creep/)

Eliminé el uso del DOM

2024-11-20 01:58 UTC, carolosano commented on script.js
> +function Cliente(nombre, email) {
> ¿Esto es una Clase? ¿Porque tiene la sintaxis de function y no de class? Revisar la [sintaxis](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes) correcta, además como dijimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009), es propio tener las clases en un archivo aparte.

Directamente elimine esto e hice las clases para los packs y para los clientes en el form de contacto
<img width="415" alt="Captura de pantalla 2024-11-19 a las 10 57 48 p  m" src="https://github.com/user-attachments/assets/9c066721-d8b3-400b-8cea-20d1504701ad">

2024-11-20 01:59 UTC, carolosano commented on script.js
> +    this.mostrarInfo = function() {
> No es la sintaxis correcta de [métodos](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes#m%C3%A9todos_prototipo), suponiendo que se trate de eso. Revisar

Aca cambie el metodo
<img width="533" alt="Captura de pantalla 2024-11-19 a las 10 58 39 p  m" src="https://github.com/user-attachments/assets/5078bfc5-dba2-44b6-a54b-8f52e7510868">

2024-11-20 01:59 UTC, carolosano commented on script.js
> +function Consulta(cliente, mensaje) {
> ¿Esto es una Clase? ¿Porque tiene la sintaxis de function y no de class? Revisar la [sintaxis](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes) correcta, además como dijimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009), es propio tener las clases en un archivo aparte.

elimine esta clase

2024-11-20 01:59 UTC, carolosano commented on script.js
> +    this.mostrarConsulta = function() {
> No es la sintaxis correcta de [métodos](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes#m%C3%A9todos_prototipo), suponiendo que se trate de eso. Revisar

Aca directamente hice que muestre la consulta en consola
![Uploading Captura de pantalla 2024-11-19 a las 10.59.33 p. m..png…]()

2024-11-20 02:00 UTC, carolosano commented on script.js
> +    var nombre = document.getElementById('nombre').value;
elimine el DOM

2024-11-20 02:00 UTC, carolosano commented on script.js
> +    if (packSeleccionado === "1") {
UTILICE EL SWITCH


<img width="420" alt="Captura de pantalla 2024-11-19 a las 10 59 33 p  m" src="https://github.com/user-attachments/assets/1dfbea40-c18f-4e13-9609-4430b1bc16d2">
<img width="419" alt="Captura de pantalla 2024-11-19 a las 11 00 27 p  m" src="https://github.com/user-attachments/assets/606c2d04-72a1-4c6f-9145-78e8a935f58a">

2024-11-20 02:01 UTC, carolosano commented on script.js
> +function saludar(nombre, mensaje) {
Elimine esta funcionalidad directamente. no tiene sentido, era para probar que funcionaba,

2024-11-20 02:02 UTC, carolosano commented on script.js
> +function elegirPack() {
aca le puse la función junto con el switch para que el usuario elija el pack que quiera
<img width="564" alt="Captura de pantalla 2024-11-19 a las 11 02 03 p  m" src="https://github.com/user-attachments/assets/31dfdb1f-ea97-428e-a962-9079d0bc6cc4">
<img width="490" alt="Captura de pantalla 2024-11-19 a las 11 02 06 p  m" src="https://github.com/user-attachments/assets/b72cec95-9fef-45ce-8959-fb6796094545">

2024-11-20 02:03 UTC, carolosano commented on script.js
> +    event.preventDefault();  // Prevenir el envío del formulario
elimine el dom

2024-11-20 18:39 UTC, carolosano commented
@MVelasquez98 ahi agregue footer y mapa que me faltaba. pero el resto de los cambios los tengo me parece, el formulario esta con promts y console.log con una **function manejarFormulario** . 

- tambien cree para usar la clase Producto en donde arma un objeto con los datos del pack:
<img width="1110" alt="Captura de pantalla 2024-11-20 a las 3 36 05 p  m" src="https://github.com/user-attachments/assets/94c0bcbe-43b4-427a-b031-f08f3d494e6c">

- tambien al Armar Pack le agregué un Switch con un prompt y que se muestre el pack armado en consola.
<img width="423" alt="Captura de pantalla 2024-11-20 a las 3 38 07 p  m" src="https://github.com/user-attachments/assets/eb26430f-227d-4d89-a352-16143ced8f1e">

-cambie un par de cosas mas como la eliminación del DOM que me pediste y la creación de una clase  PackAlternativo para armar su propio pack (el usuario)

2024-11-20 18:42 UTC, MVelasquez98 commented
¿Revisaste el código que te comparti del [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009)? Las clases que utilizas van en archivos separados
![image](https://github.com/user-attachments/assets/9eeb3ced-0e86-4330-8b36-fe4f89a60b1c)

2024-11-20 18:45 UTC, MVelasquez98 commented
Entra a la pestaña [files changed](https://github.com/carolosano/carolosano.github.io/pull/7/files) revisa todos los comentarios de review:
![image](https://github.com/user-attachments/assets/e12230e0-b535-4b53-a36d-588908f8223b)

2024-11-20 18:47 UTC, carolosano commented
> ¿Revisaste el código que te comparti del [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009)? Las clases que utilizas van en archivos separados ![image](https://private-user-images.githubusercontent.com/43156596/388222619-9eeb3ced-0e86-4330-8b36-fe4f89a60b1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjg2NDcsIm5iZiI6MTczMjEyODM0NywicGF0aCI6Ii80MzE1NjU5Ni8zODgyMjI2MTktOWVlYjNjZWQtMGU4Ni00MzMwLThiMzYtZmU0Zjg5YTYwYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE4NDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiZTQwZmVjMjU0NGQ1MzdjMDAwNDgxYmZlMjcxNjg4MWIzZjE5ODZjMmVkNjA1NzVmNThmYmM5YWUwY2QxNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.exlbIwecYZZMzjDg8CQQxO14C0Z0oGQkVRB4pPNN2aU)

Si vi la clase y lo intenté pero me pasó que aunque ponga type=“module” me daba error. Entonces como vi que no afectaba en mi codigo poner la clase dentro del main lo dejé asi

2024-11-20 18:52 UTC, MVelasquez98 commented
Tienen que estaren archivos aparte, no podes hacer un export dentro del mismo archivo.
¿Que error te generaba? ¿Pusiste los import y export correspondientes?

2024-11-20 19:27 UTC, carolosano commented
> Tienen que estar en archivos aparte, no podes hacer un export dentro del mismo archivo. ¿Que error te generaba? ¿Pusiste los import y export correspondientes?

Ahi estoy viendo devuelta y me di cuenta que los export estaban mal por eso. ahi hago hago el push para que veas los cambios.

2024-11-20 19:50 UTC, MVelasquez98 commented
Revisar comentarios pendientes

2024-11-20 19:54 UTC, carolosano reviewed
Ahi vi todos los comentarios

2024-11-20 22:42 UTC, carolosano reviewed
?

2024-11-20 23:05 UTC, carolosano commented
@MVelasquez98  Mando punteo de lo que hice porque no se que falta que me estoy perdiendo. Asi que respondo devuelta al punteo que me hiciste para verlo juntos para ver que me falta para que me des el LGTM:

PUNTAJE POR CONSIGNA:
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

Algoritmos (1 punto)
❌ 0 puntos: Uso incorrecto o ineficiente de algoritmos condicionales y ciclos. No estas usando switch, no estas usando un ciclo para el menu, solo se va ver una vez.

**- Hice un switch + prompt para simular la elección del pack "Armar tu propio Pack"**

<img width="665" alt="Captura de pantalla 2024-11-20 a las 7 47 34 p  m" src="https://github.com/user-attachments/assets/6e5db771-155f-4b32-be51-29799a0b4008">
<img width="508" alt="Captura de pantalla 2024-11-20 a las 7 47 46 p  m" src="https://github.com/user-attachments/assets/7b59dd75-32c8-427e-993d-89f0f42a516a">



Funciones (1 punto)
❌ 0 puntos: Funciones con nombres confusos, estructura incorrecta o resultados incorrectos. Estas confundiendo funciones con clases en sintaxis. Recorda que funciones y métodos son diferentes sintaxis.

**- Corregí e hice  la separación de funciones y clases con métodos. Por ejemplo en Producto:**

<img width="623" alt="Captura de pantalla 2024-11-20 a las 7 52 08 p  m" src="https://github.com/user-attachments/assets/6e58331d-3df0-4efd-8287-4a3db10d4b19">

**- O para el simulador del formulario:**

<img width="814" alt="Captura de pantalla 2024-11-20 a las 7 53 06 p  m" src="https://github.com/user-attachments/assets/e86e3df1-8e2a-438a-bf56-56b95fd12367">


Funcionalidad (1 punto)
❌ 0 puntos: Flujo de trabajo incompleto o funcionalidad inapropiada al contexto. Tu algoritmo no resuelve nada funcional para la pagina, solo hay una validación de un nombre y una validación de formulario (que utiliza eventos y DOM que no vimos en la unidad y no entra en esta entrega). Se espera algun algoritmo relacionado con calcular un precio, filtrar o buscar productos, armar un carrito de compras, etc. El menu propuesto de agregarPack es interesante, pero nunca se llama de ningun lado.

**- Tengo para armar un carrito/ pack con el Switch que mostré anteriormente. "armarPack":**
<img width="537" alt="Captura de pantalla 2024-11-20 a las 7 55 03 p  m" src="https://github.com/user-attachments/assets/ef3db64b-0f10-4e70-998e-79b764618549">
<img width="422" alt="Captura de pantalla 2024-11-20 a las 7 55 44 p  m" src="https://github.com/user-attachments/assets/bf1e73b5-a745-431c-aee4-cf1a0edb3839">
<img width="175" alt="Captura de pantalla 2024-11-20 a las 7 55 26 p  m" src="https://github.com/user-attachments/assets/b88efe82-429e-4ab4-873a-e9b6bb08d79f">


Interactividad (1 punto)
⚠️ 0.5 puntos: Interactividad insuficiente o salidas incoherentes. Hay un solo prompt pidiendo el nombre, el resto de entradas son con DOM, que no entra en esta entrega.

- Ahora tengo 2 prompts (uno para armar el pack y otro para el formulario de contacto) Tambien se ven en consola ambos, y el resto de las funcionalidades

<img width="436" alt="Captura de pantalla 2024-11-20 a las 7 59 36 p  m" src="https://github.com/user-attachments/assets/42d06d84-740f-482e-ade1-686ed39cf8df">


Escalabilidad (1 punto)
❌ 0 puntos: Falta de funciones con parámetros, arrays o objetos relevantes. No utilizas clases ni métodos con la sintaxis correcta, no utilizas arrays.

**- Array tengo para almacenar la cantidad de productos en armar pack y objeto tambien que se arma un objeto con nombre, apellido, empresa y mensaje:**

<img width="561" alt="Captura de pantalla 2024-11-20 a las 8 01 14 p  m" src="https://github.com/user-attachments/assets/0a17a299-2eb5-4e5d-b11e-f677b2bfc95b">


Legibilidad (1 punto)
⚠️ 0.5 puntos: Nombres de variables, funciones u objetos poco significativos, código ilegible o mal estructurado. Cuesta seguir el hilo de cual es la funcionalidad que estas buscando, seprar correctamente las clases en archivos separaos y definir correctamente las funciones te va ayudar.

- Estructure mejor el HTML y el JS con comentarios (pido disculpas los comentarios en el codigo pero es para no perder las cosas del DOM que había echo.

GitHub (4 puntos):
✅ 1 punto: Creación de una rama "backport/primer-parcial" a partir de la rama "master" utilizando Git.
✅ 1 punto: Creación de una rama "feature/tercera-entrega" a partir de la rama "develop" utilizando Git.
⚠️ 0.5 puntos:: Correcta realización de la solicitud de revisión para fusionar la rama "backport/primer-parcial" con "develop" en GitHub, resolviendo los conflictos de merge (si fuese necesario). Cuidado con las pr cerradas sin merge, no es una buena practica, en algunos lugares esto reporta una métrica negativa.
⚠️ 0.5 puntos: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "release/primer-parcial" con "master" en GitHub, resolviendo los conflictos de merge (si fuese necesario). Faltaron puntos de responsive por solucionar, entre los cambios solicitados.

2024-11-21 02:47 UTC, MVelasquez98 commented
Me refiero a estos comentarios en review changes:
<img width="545" alt="image" src="https://github.com/user-attachments/assets/71825c9c-b0d2-4dc2-a3ab-01ad6f23b8db">
<img width="555" alt="image" src="https://github.com/user-attachments/assets/f5e97fa2-ce82-482a-8f58-6d74c1cda28a">

2024-11-21 02:54 UTC, carolosano commented
> Me refiero a estos comentarios en review changes: <img alt="image" width="545" src="https://private-user-images.githubusercontent.com/43156596/388333885-71825c9c-b0d2-4dc2-a3ab-01ad6f23b8db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTc4MDQsIm5iZiI6MTczMjE1NzUwNCwicGF0aCI6Ii80MzE1NjU5Ni8zODgzMzM4ODUtNzE4MjVjOWMtYjBkMi00ZGMyLWEzYWItMDFhZDZmMjNiOGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAyNTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZGZmYTI2NTQ4OWQzNDMxMzA3ZDkyYTViN2RlNGFmNWRkMmY5ZTMwNTU5OTUwNmNiNjBjM2NhZDRlM2VlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ii1CZUukWtVvte9xDiZqRB7frrdYVn9fmOlSeOkSdHA"> <img alt="image" width="555" src="https://private-user-images.githubusercontent.com/43156596/388334061-f5e97fa2-ce82-482a-8f58-6d74c1cda28a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTc4MDQsIm5iZiI6MTczMjE1NzUwNCwicGF0aCI6Ii80MzE1NjU5Ni8zODgzMzQwNjEtZjVlOTdmYTItY2U4Mi00ODJhLThmNTgtNmQ3NGMxY2RhMjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAyNTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkOGE4MzVkYWE5ZDdmZDk0NzgyYWEwOWUyMTkxMWIwNzcwODIwMTVlMzUzYmM3YmEzZGNiZDlkNTFiMTFjYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hQwYuhmJKyGkSFGxnqthqvf-BwNaKri6uBjljQ13l2k">

Ahh claro, no logro encontrar esa parte donde tenes los comentarios, les mostre a alguno de los chicos para ver que era lo que me faltaba y les pasó lo mismo 😅 que no pudieron ver donde estaba la review. Ahora veo eso y lo corrijo. Perdoname que te joda, hay algo mas a prte de eso? porque sigo sin encontrar del link de las reviews q me psaste eso.😅

2024-11-21 12:14 UTC, carolosano commented
@MVelasquez98 Buen dia profe, ahi hice esos dos últimos cambios que me mandaste screenshot. No me sale ninguna mas, capaz no las estoy pudiendo ver en caso de que me falte alguna. Avisame. Saludos
<img width="417" alt="Captura de pantalla 2024-11-21 a las 9 13 37 a  m" src="https://github.com/user-attachments/assets/c20bf83d-e5d2-4669-a6f8-334d5e0ea79e">

2024-11-21 12:35 UTC, MVelasquez98 commented
Revisar último comentario, te quedaron las instancias exportadas que no corresponde, por que no estan definidas

2024-11-21 13:16 UTC, carolosano commented
@MVelasquez98 claro, había cambiado de lugar las instancias pero dejé la exportación en el otro archivo producto.js. Ahi lo corregí.

2024-11-21 13:22 UTC, MVelasquez98 approved these changes
LGTM

2024-11-21 13:22 UTC, MVelasquez98 commented on script.js
> +class Producto {
Las clases van en archivos aparte, por ejemplo `Producto.js`. Revisa los otros comentarios que te deje

2024-11-21 13:22 UTC, MVelasquez98 commented on script.js
> +  class PackAlternativo {
Las clases van en archivos aparte, por ejemplo `PackAlternativo.js`. Revisa los otros comentarios que te deje

2024-11-21 13:22 UTC, MVelasquez98 commented on script.js
> +//document.getElementById("contact-form").addEventListener("submit", function(event) {
No es buena practica dejar codigo comentado, lo recomendable por eso es que esto este en la rama `feature/cuarta-entrega` o bien podes crear un archivo de texto aparte y guardar esto aparte.

2024-11-21 13:22 UTC, MVelasquez98 commented on script.js
> +function Cliente(nombre, email) {
> ¿Esto es una Clase? ¿Porque tiene la sintaxis de function y no de class? Revisar la [sintaxis](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes) correcta, además como dijimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009), es propio tener las clases en un archivo aparte.

A este comentario me refiero

2024-11-21 13:22 UTC, MVelasquez98 commented on script.js
> +function Cliente(nombre, email) {
Lass clases van en archivos apartes, lo puse en los comentarios, fijate como lo hicimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009)

2024-11-21 13:22 UTC, MVelasquez98 commented on script.js
> +function Consulta(cliente, mensaje) {
No hay que eliminar el uso de clases, sino usarlas en archivos aparte como lo hicimos en el [encuentro](https://github.com/MVelasquez98/Programaci-n-Web-I---UCES/tree/feature/tercera-entrega/Clase%2009)

2024-11-21 13:22 UTC, MVelasquez98 commented on script.js
> +//document.getElementById("contact-form").addEventListener("submit", function(event) {
Esto no resolviste

2024-11-21 13:22 UTC, MVelasquez98 commented on Producto.js
> +  const packGrafico = new Producto(
Las instancias no son necesarias ponerlas en este archivo, aca solo va el modelo de la Clase, las instancias en el main (script.js)

2024-11-21 13:22 UTC, MVelasquez98 commented on Producto.js
> +  const packGrafico = new Producto(
Revisar esto

2024-11-21 13:22 UTC, MVelasquez98 commented on Producto.js
> +  export { Producto, packGrafico, packPublicitario };
Remover **packGrafico, packPublicitario** ya que no esta definido

2024-11-21 13:22 UTC, MVelasquez98 commented on Producto.js
> +export { Producto };
Las llaves estan de mas

2024-11-21 13:37 UTC, merged