Commit N1 pull request feature cuarta-entrega
carolosano/carolosano.github.io pull request #8
Opened 2024-11-22 13:14 UTC by carolosano

2024-11-27 00:33 UTC, carolosano commented
@MVelasquez98 hola profe. queria saber si tenia alguna corrección para hacer

2024-11-27 00:56 UTC, MVelasquez98 commented
No te olvides de hacer deploy en GiHubPAges de esta rama, para poder visualizar y probar los cambios que realizaste:
![image](https://github.com/user-attachments/assets/efed4ae5-0193-4646-ad43-ae0a1523daac)

2024-11-27 13:35 UTC, carolosano commented
> No te olvides de hacer deploy en GiHubPAges de esta rama, para poder visualizar y probar los cambios que realizaste: ![image](https://private-user-images.githubusercontent.com/43156596/390204771-efed4ae5-0193-4646-ad43-ae0a1523daac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTQ4MDgsIm5iZiI6MTczMjcxNDUwOCwicGF0aCI6Ii80MzE1NjU5Ni8zOTAyMDQ3NzEtZWZlZDRhZTUtMDE5My00NjQ2LWFkNDMtYWUwYTE1MjNkYWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEzMzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OTY3MzE3ZGMwZDJiZjEwNjljMDlkMTEzMWE5MDcyMzYwM2E5MGU1MDRhYTNkMWE3MWM0NGQ3ODA0ZWU2MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gtu1hx5bh-YFIeiJXqFx1I6cwApXTbDq8Bgdo1wsGF0)

@MVelasquez98 tenes razón, ahi hice el deploy para que se vea en Pages !

2024-11-27 16:10 UTC, MVelasquez98 commented
Este flujo no refleja un algotitmo de Entrada - Proceso - Salida
![image](https://github.com/user-attachments/assets/23775993-1308-4cb4-a902-84b8124d1a25)
¿Que seria un pack creado?¿A que referencian esos numeros?¿Por qué no dibujar en el dom algo más para el usuario? Precio, que incluye el pack, una cotización, un carrito. Solo es un boton que imprime alertas

2024-11-27 16:11 UTC, MVelasquez98 commented
Revisar comentarios

2024-11-27 22:19 UTC, carolosano commented
@MVelasquez98 fíjate ahi hice un carrito que te calcula el precio total de todos los precios unitarios de cada check y lo guarda en el local Storage.

2024-11-27 22:22 UTC, carolosano commented
@MVelasquez98 otra cosa que estuve viendo con mis compañeros es que yo no se por que no puedo ver sus comentarios en mi codigo en la sección de "files changed", mire.
<img width="1476" alt="Captura de pantalla 2024-11-27 a las 7 20 04 p  m" src="https://github.com/user-attachments/assets/a27325f6-55a0-415f-96e0-bc31994a2aaa">

nose si me habrá mandado mas comentarios pero yo apretó el archivo de script y sigo si poder visualizar sus comentarios, nose si es algo que tengo que activar desde configuración, me vi un par de videos pero no me resolvieron el problema

2024-11-27 22:22 UTC, MVelasquez98 commented
Revisar comentarios en [files changed](https://github.com/carolosano/carolosano.github.io/pull/8/files)

2024-11-27 22:24 UTC, MVelasquez98 commented
Baja hasta el archivo [script.js](https://github.com/carolosano/carolosano.github.io/pull/8/files#diff-ed3ee7e0beea2498ff3b8ca85973d122fc6fa3d585d62b5807ec034d0cf076b3)
Fijate arriba te indica la cantidad de comentarios sin revisar:
![image](https://github.com/user-attachments/assets/4788dd8c-4ed9-484c-a89e-1f3c9ec3a6b2)

2024-11-27 22:32 UTC, carolosano commented
> Baja hasta el archivo [script.js](https://github.com/carolosano/carolosano.github.io/pull/8/files#diff-ed3ee7e0beea2498ff3b8ca85973d122fc6fa3d585d62b5807ec034d0cf076b3) Fijate arriba te indica la cantidad de comentarios sin revisar: ![image](https://private-user-images.githubusercontent.com/43156596/390581403-4788dd8c-4ed9-484c-a89e-1f3c9ec3a6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NDY5MDksIm5iZiI6MTczMjc0NjYwOSwicGF0aCI6Ii80MzE1NjU5Ni8zOTA1ODE0MDMtNDc4OGRkOGMtNGVkOS00ODRjLWE4OWUtMWYzYzllYzNhNmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDIyMzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTg0ZmQ0ZjJkOGYwMWVlZTVlMWRjNTMxYjNlZjM1MTAwODAwOWY5ZGRmOTY4MTk5MmFmNzI4MmQ1OGM0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rU7gfvHC6AoZyFeD144qFejBEtAU_gNzxJh-yRpWMi0)

@MVelasquez98 me aparece asi mira: y toco en el botón de reviértame changes pero me sale para que comento yo

<img width="1478" alt="Captura de pantalla 2024-11-27 a las 7 30 05 p  m" src="https://github.com/user-attachments/assets/f416fac7-0074-43c0-984c-7774b7df6749">

<img width="1483" alt="Captura de pantalla 2024-11-27 a las 7 31 32 p  m" src="https://github.com/user-attachments/assets/710065ea-06ad-45d6-896b-29d7bad3b005">

2024-11-27 22:35 UTC, carolosano commented
@MVelasquez98 
https://github.com/user-attachments/assets/879b212a-579e-453c-a13c-70a6ae8108a8

2024-11-27 23:00 UTC, carolosano commented
> @MVelasquez98 https://github.com/user-attachments/assets/879b212a-579e-453c-a13c-70a6ae8108a8

Aca mando video de lo que me aparece **(no me aparece que tengo 3 cambios para hacer en ningún lado)**
https://github.com/user-attachments/assets/d8588e11-aa17-436b-9bb7-03dcd2dcef83

2024-11-27 23:23 UTC, MVelasquez98 requested changes

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +    alert("Su mensaje se ha enviado con éxito");
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Evitemos alert. Podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [SweetAlert](https://sweetalert2.github.io/)

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +      alert(`¡Pack ${listaPacks.length} creado con éxito!`);
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Evitemos alert. Podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [SweetAlert](https://sweetalert2.github.io/)

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +      alert('Por favor selecciona al menos una opción para crear un pack.');
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Evitemos alert. Podes incluso usar [modales](https://getbootstrap.com/docs/4.1/components/modal/), o hasta animarte a usar alguna lib de js como [SweetAlert](https://sweetalert2.github.io/)

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +      alert('¡Gracias por tu compra! Los detalles de tu pack han sido guardados.');
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Evitemos alert. Podes incluso usar modales, o hasta animarte a usar alguna lib de js como SweetAlert

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +      alert('Tu carrito está vacío. Por favor selecciona servicios.');
Aunque el uso de alert es útil, puede causar una mala experiencia de usuario. Evitemos alert. Podes incluso usar modales, o hasta animarte a usar alguna lib de js como SweetAlert

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +    alert("Su mensaje se ha enviado con éxito");
@carolosano

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +      alert(`¡Pack ${listaPacks.length} creado con éxito!`);
@carolosano

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +      alert('Por favor selecciona al menos una opción para crear un pack.');
@carolosano

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +      alert('¡Gracias por tu compra! Los detalles de tu pack han sido guardados.');
@carolosano

2024-11-27 23:23 UTC, MVelasquez98 commented on script.js
> +      alert('Tu carrito está vacío. Por favor selecciona servicios.');
@carolosano

2024-11-28 02:43 UTC, MVelasquez98 commented
![image](https://github.com/user-attachments/assets/e650ebd5-d889-487f-9654-83072cee84c0)

2024-11-28 03:55 UTC, carolosano commented
@MVelasquez98 ahi hice el deploy con los cambios. avisame si me falta algo mas, creo que no

2024-11-28 13:05 UTC, MVelasquez98 requested changes

2024-11-28 13:05 UTC, MVelasquez98 commented on script.js
> +import PackAlternativo from "./packAlternativo.js";
Esta Clase nunca la usas

2024-11-28 13:05 UTC, MVelasquez98 commented on script.js
> +  const pack = {
¿Por que no usar la clase PackAlternativo?

2024-11-28 13:05 UTC, MVelasquez98 commented on script.js
> +    localStorage.setItem("contacto", JSON.stringify(datosContacto));
No hay validación de campos vacíos antes de guardar los datos. Esto puede resultar en entradas no deseadas.
```suggestion
if (!nombre || !apellido || !empresa || !mensaje) {
  Swal.fire({
    title: "Error",
    text: "Por favor, completa todos los campos.",
    icon: "warning",
    confirmButtonText: "Aceptar",
  });
  return;
}
```

2024-11-28 13:05 UTC, MVelasquez98 commented on script.js
> +window.armarPack = armarPack;
Las funciones armarPack y finalizarCompra se exportan, pero también se asignan a window. Si este comportamiento no es estrictamente necesario, es mejor evitar la asignación global.

2024-11-28 13:05 UTC, MVelasquez98 commented on script.js
> +export function finalizarCompra() {
¿Por que exportas esta funcion?¿Donde se usa?

2024-11-28 13:05 UTC, MVelasquez98 commented on script.js
> +export function armarPack() {
¿Por que exportas esta funcion?¿Donde se usa?

2024-11-28 13:05 UTC, MVelasquez98 commented
Revisar comentarios

2024-11-28 13:08 UTC, MVelasquez98 commented
¿Ves esto? 
![image](https://github.com/user-attachments/assets/31272415-c417-48d2-9303-b7ed814ba031)
Si haces click en [view review changes](https://github.com/carolosano/carolosano.github.io/pull/8/files/e4d14b18aa73e8bc1a0b9b9316f8d8e333825bec), te lleva aca
![image](https://github.com/user-attachments/assets/4e644def-bc66-4fe9-979b-6553673912aa)
Aca no vas a ver nada hasta que recorras hasta abajo todo el archivo en busca de comentarios en cada linea de codigo:
![image](https://github.com/user-attachments/assets/f3dabd72-d76d-4b41-84d5-31222eabd722)

2024-11-28 13:09 UTC, MVelasquez98 commented
Una vez que ya resolviste un comentario le das "resolve conversation"
![image](https://github.com/user-attachments/assets/294fb306-919d-485e-9343-52e1a82c9bc1)

2024-11-28 14:01 UTC, carolosano commented
@MVelasquez98 hola profe ahi hice los cambios. avisame cualquier cosa

2024-11-28 14:13 UTC, MVelasquez98 requested changes

2024-11-28 14:13 UTC, MVelasquez98 commented on index.html
>          <button id="botonArmarPack" class="boton-armar-pack" onclick="armarPack()">Armar Pack</button>
Esto esta mal, no asociamos asi los eventos, lo hacemos directamente en js:
```suggestion
       document.getElementById("btnArmarPack").addEventListener("click", armarPack);
```

2024-11-28 14:13 UTC, MVelasquez98 commented on index.html
> +        <button id="finalizarCompra" class="btn-finalizar" onclick="finalizarCompra()">Finalizar Compra</button>
Esto esta mal, no asociamos asi los eventos, lo hacemos directamente en js, no en el HTML incrustado:
```suggestion
document.getElementById("btnFinalizarCompra").addEventListener("click", finalizarCompra);

```

2024-11-28 14:13 UTC, MVelasquez98 commented on script.js
> +window.armarPack = armarPack;
Evitar el uso del objeto global window En lugar de exponer las funciones al objeto global, podes vincularlas directamente a los eventos desde JavaScript. Esto hace que el código sea más modular y evita contaminación del espacio global.

2024-11-28 14:13 UTC, MVelasquez98 commented on script.js
> +window.armarPack = armarPack;
```suggestion
document.getElementById("btnArmarPack").addEventListener("click", armarPack);
```

2024-11-28 14:13 UTC, MVelasquez98 commented on script.js
> +window.finalizarCompra = finalizarCompra;
```suggestion
document.getElementById("btnFinalizarCompra").addEventListener("click", finalizarCompra);
```

2024-11-28 14:31 UTC, carolosano commented
@MVelasquez98 ahi hice esos últimos cambios profe. del windows y el evento incrustado en el html. avisame

2024-11-28 14:34 UTC, MVelasquez98 requested changes

2024-11-28 14:34 UTC, MVelasquez98 commented on script.js
> +document.getElementById("botonArmarPack").addEventListener("click", armarPack);
Esto esta repetido, si haces lo de arriba ya estas asignando el evento, es uno o el otro, si no estas asignando el evento dos veces

2024-11-28 14:34 UTC, MVelasquez98 commented on script.js
> +document.getElementById("finalizarCompra").addEventListener("click", finalizarCompra);
Esto esta repetido, si haces lo de arriba ya estas asignando el evento, es uno o el otro, si no estas asignando el evento dos veces

2024-11-28 14:45 UTC, MVelasquez98 requested changes

2024-11-28 14:45 UTC, MVelasquez98 commented on script.js
> +//document.getElementById("botonArmarPack").addEventListener("click", armarPack);
Evita comentar codigo, si no se usa, se elimina.

2024-11-28 14:57 UTC, carolosano commented on script.js
> +    alert("Su mensaje se ha enviado con éxito");
listo perfecto ahi puse un sweet alert para eso. tenes razón me pareció mucho mejor usando el sweetalert (fue todo un tema coordinar pero PUDE! jajaja)

2024-11-28 14:57 UTC, carolosano commented on script.js
> +      alert(`¡Pack ${listaPacks.length} creado con éxito!`);
listo

2024-11-28 14:57 UTC, carolosano commented on script.js
> +      alert('Tu carrito está vacío. Por favor selecciona servicios.');
listo

2024-11-28 14:57 UTC, carolosano commented on script.js
> +      alert('¡Gracias por tu compra! Los detalles de tu pack han sido guardados.');
listo

2024-11-28 14:57 UTC, carolosano commented on script.js
> +      alert('Por favor selecciona al menos una opción para crear un pack.');
listo

2024-11-28 14:57 UTC, carolosano commented on script.js
> +window.armarPack = armarPack;
es que me pasó que si no lo hacia global me daba este error: `ReferenceError: Can't find variable: armarPack`

2024-11-28 14:57 UTC, carolosano commented on script.js
> +export function armarPack() {
me pasaba lo mismo que armar pack, como q no podia encontrar la variable me decía y la solución q encontré fue exportarlo :\

2024-11-28 14:57 UTC, carolosano commented on script.js
> +window.armarPack = armarPack;
ahi saque su exportacion y al parecer funciona bien creo. la asignación a window se la deje porque ahi vuelve a decirme `Can't find variable: armarPack`

2024-11-28 14:57 UTC, carolosano commented on script.js
> +document.getElementById("finalizarCompra").addEventListener("click", finalizarCompra);
a claro entonces saco estos:
document.getElementById("botonArmarPack").addEventListener("click", armarPack);
document.getElementById("finalizarCompra").addEventListener("click", finalizarCompra);
 
 y dejo los dos de arriba:

const botonArmarPack = document.getElementById("botonArmarPack");
const botonFinalizarCompra = document.getElementById("finalizarCompra");

botonArmarPack.addEventListener("click", armarPack);
botonFinalizarCompra.addEventListener("click", finalizarCompra);

2024-11-28 14:57 UTC, carolosano commented on script.js
> +document.getElementById("finalizarCompra").addEventListener("click", finalizarCompra);
hago el push para q veas

2024-11-28 14:59 UTC, carolosano commented
@MVelasquez98 ahi saque el comment

2024-11-28 15:36 UTC, MVelasquez98 approved these changes
LGTM

2024-11-28 16:13 UTC, merged